# -*- coding: utf-8 -*-
"""RESEARCHWITH ACC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vel89qUX_tP1kl65Gpnc8aXoweP6nnCh
"""

# ============================================================
# 📦 INSTALL & IMPORTS
# ============================================================

!pip install -q tensorflow seaborn scikit-learn

import os, random, time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16, ResNet50, EfficientNetB0
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve, auc

from tensorflow.keras.preprocessing import image as keras_image

from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# ⚙️ CONFIGURATION
# ============================================================

DATA_PATH   = "/content/drive/MyDrive/research dataset/Alzheimer (Preprocessed Data)"
IMG_SIZE    = 224
BATCH_SIZE  = 32
NUM_CLASSES = 4

# ============================================================
# 🧠 DATA GENERATORS
# ============================================================

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_data = train_datagen.flow_from_directory(
    DATA_PATH,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

val_data = val_datagen.flow_from_directory(
    DATA_PATH,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

class_names = list(train_data.class_indices.keys())

print("Classes:", class_names)
print(f"Train samples: {train_data.samples}")
print(f"Validation samples: {val_data.samples}")

# ============================================================
# 🔁 CALLBACKS
# ============================================================

def get_callbacks():
    return [
        EarlyStopping(monitor='val_accuracy', patience=6, restore_best_weights=True),
        ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3, min_lr=1e-7)
    ]

# ============================================================
# 🧱 CUSTOM CNN
# ============================================================

def build_cnn():
    model = models.Sequential([
        layers.Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE,IMG_SIZE,3)),
        layers.BatchNormalization(),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(64, (3,3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(128, (3,3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(256, (3,3), activation='relu'),
        layers.BatchNormalization(),
        layers.GlobalAveragePooling2D(),

        layers.Dense(256, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.3),

        layers.Dense(NUM_CLASSES, activation='softmax')
    ])

    model.compile(
        optimizer=Adam(1e-3),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

# ============================================================
# 🔄 TRANSFER LEARNING MODEL
# ============================================================

def build_transfer_model(base_model):
    base_model.trainable = False

    inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    x = base_model(inputs, training=False)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()

    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.4)

    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.3)

    outputs = layers.Dense(NUM_CLASSES, activation='softmax')(x)

    model = tf.keras.Model(inputs, outputs)

    model.compile(
        optimizer=Adam(1e-4),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

# ============================================================
# 📊 EVALUATION FUNCTION
# ============================================================

def evaluate_model(model, val_data, name):
    val_data.reset()

    preds = model.predict(val_data)
    y_pred = np.argmax(preds, axis=1)
    y_true = val_data.classes

    loss, acc = model.evaluate(val_data)

    print(f"\n{name} Results:")
    print(f"Accuracy: {acc*100:.2f}%")
    print(f"Loss: {loss:.4f}")

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title(name + " Confusion Matrix")
    plt.show()

# ============================================================
# 🚀 TRAIN CUSTOM CNN
# ============================================================

cnn = build_cnn()

history_cnn = cnn.fit(
    train_data,
    validation_data=val_data,
    epochs=30,
    callbacks=get_callbacks()
)

evaluate_model(cnn, val_data, "Custom CNN")

# ============================================================
# 🚀 TRAIN VGG16
# ============================================================

base_vgg = VGG16(weights='imagenet', include_top=False, input_shape=(IMG_SIZE,IMG_SIZE,3))
vgg_model = build_transfer_model(base_vgg)

history_vgg = vgg_model.fit(
    train_data,
    validation_data=val_data,
    epochs=30,
    callbacks=get_callbacks()
)

evaluate_model(vgg_model, val_data, "VGG16")

# ============================================================
# 🚀 TRAIN RESNET50
# ============================================================

base_resnet = ResNet50(weights='imagenet', include_top=False, input_shape=(IMG_SIZE,IMG_SIZE,3))
resnet_model = build_transfer_model(base_resnet)

history_resnet = resnet_model.fit(
    train_data,
    validation_data=val_data,
    epochs=30,
    callbacks=get_callbacks()
)

evaluate_model(resnet_model, val_data, "ResNet50")

# ============================================================
# 🚀 TRAIN EFFICIENTNET
# ============================================================

base_eff = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(IMG_SIZE,IMG_SIZE,3))
eff_model = build_transfer_model(base_eff)

history_eff = eff_model.fit(
    train_data,
    validation_data=val_data,
    epochs=30,
    callbacks=get_callbacks()
)

evaluate_model(eff_model, val_data, "EfficientNetB0")

# ============================================================
# 📊 FINAL METRICS TABLE
# ============================================================

models_dict = {
    "CNN": cnn,
    "VGG16": vgg_model,
    "ResNet50": resnet_model,
    "EfficientNetB0": eff_model
}

results = []

for name, model in models_dict.items():
    val_data.reset()

    preds = model.predict(val_data)
    y_pred = np.argmax(preds, axis=1)
    y_true = val_data.classes

    loss, acc = model.evaluate(val_data)

    report = classification_report(y_true, y_pred, output_dict=True)

    results.append({
        "Model": name,
        "Accuracy (%)": round(acc*100, 2),
        "Loss": round(loss, 4),
        "Precision (%)": round(report['macro avg']['precision']*100, 2),
        "Recall (%)": round(report['macro avg']['recall']*100, 2),
        "F1-Score (%)": round(report['macro avg']['f1-score']*100, 2)
    })

df = pd.DataFrame(results)
display(df)

df.to_csv("/content/drive/MyDrive/final_results.csv", index=False)
print("Saved to Drive ✅")

# ============================================================
# 🔍 RANDOM IMAGE TEST
# ============================================================

def predict_random():
    cls = random.choice(os.listdir(DATA_PATH))
    img_name = random.choice(os.listdir(os.path.join(DATA_PATH, cls)))
    path = os.path.join(DATA_PATH, cls, img_name)

    img = keras_image.load_img(path, target_size=(IMG_SIZE, IMG_SIZE))
    arr = keras_image.img_to_array(img)/255.0
    arr = np.expand_dims(arr, axis=0)

    plt.imshow(img)
    plt.title(f"Actual: {cls}")
    plt.axis('off')
    plt.show()

    for name, model in models_dict.items():
        pred = model.predict(arr)[0]
        pred_class = class_names[np.argmax(pred)]
        print(f"{name}: {pred_class} ({np.max(pred)*100:.2f}%)")

predict_random()